// <auto-generated />
using CubrisProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CubrisProject.Migrations
{
    [DbContext(typeof(ThemeParkContext))]
    [Migration("20180609075547_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("CubrisProject.Models.ThemePark", b =>
                {
                    b.Property<int>("ThemeParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("ThemeParkName");

                    b.HasKey("ThemeParkId");

                    b.ToTable("ThemeParks");
                });
#pragma warning restore 612, 618
        }
    }
}
